const btn=document.querySelector('.menu-toggle');
const nav=document.querySelector('.navlinks');
if(btn){
  btn.setAttribute('aria-label','Open navigation');
  btn.innerHTML='<span class="hamburger-line"></span><span class="hamburger-line"></span><span class="hamburger-line"></span>';
}
if(btn&&nav){btn.addEventListener('click',()=>{nav.classList.toggle('open');btn.classList.toggle('active',nav.classList.contains('open'));btn.setAttribute('aria-label',nav.classList.contains('open')?'Close navigation':'Open navigation');});}
if(nav&&!nav.querySelector('a[href="/book-a-table/"]')){const bookingLink=document.createElement('a');bookingLink.href='/book-a-table/';bookingLink.textContent='Book a Table';nav.appendChild(bookingLink);}

document.querySelectorAll('a[href]').forEach(a=>{
  const href=a.getAttribute('href');
  const clean={
    'index.html':'/',
    'menu.html':'/menu/',
    'gallery.html':'/gallery/',
    'venue-hire.html':'/venue-hire/',
    'contact.html':'/contact/'
  };
  if(clean[href]) a.setAttribute('href',clean[href]);
});

document.querySelectorAll('.navlinks a').forEach(a=>a.addEventListener('click',()=>{if(nav)nav.classList.remove('open');if(btn)btn.classList.remove('active');}));

const ASSET_VERSION='6.7';
document.querySelectorAll('img[src^="assets/"]').forEach(img=>{const base=img.getAttribute('src').split('?')[0];img.setAttribute('src',`${base}?v=${ASSET_VERSION}`);});
document.querySelectorAll('[style*="assets/"]').forEach(el=>{const style=el.getAttribute('style');el.setAttribute('style',style.replace(/(assets\/[A-Za-z0-9._-]+\.(?:webp|png|jpg|jpeg))(?:\?v=[^'\")]+)?/g,`$1?v=${ASSET_VERSION}`));});

document.querySelectorAll('.brand span').forEach(el=>{el.textContent='52 South Cafe & Restaurant';});
document.querySelectorAll('.brand img').forEach(img=>{img.style.borderRadius='50%';img.style.objectFit='cover';});
const FACEBOOK_URL='https://www.facebook.com/share/1HKZzzKNUb/?mibextid=wwXIfr';
const INSTAGRAM_URL='https://www.instagram.com/52south.au?igsi=MXIwc3phMmdqM2Jkcg%3D%3D&utm_source=qr';
const fbIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M13.5 22v-9h3l.5-3h-3.5V8.1c0-.9.3-1.6 1.8-1.6H17V3.8c-.5-.1-1.3-.2-2.4-.2-2.4 0-4.1 1.5-4.1 4.2V10H8v3h2.5v9h3z"/></svg>';
const igIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M7 2h10a5 5 0 0 1 5 5v10a5 5 0 0 1-5 5H7a5 5 0 0 1-5-5V7a5 5 0 0 1 5-5zm0 2a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h10a3 3 0 0 0 3-3V7a3 3 0 0 0-3-3H7zm10.5 1.5a1.2 1.2 0 1 1 0 2.4 1.2 1.2 0 0 1 0-2.4zM12 7a5 5 0 1 1 0 10 5 5 0 0 1 0-10zm0 2a3 3 0 1 0 0 6 3 3 0 0 0 0-6z"/></svg>';
if(nav&&!nav.querySelector('.nav-socials')){const socialWrap=document.createElement('div');socialWrap.className='nav-socials';socialWrap.innerHTML=`<a class="social-icon" href="${FACEBOOK_URL}" target="_blank" rel="noopener" aria-label="52 South on Facebook">${fbIcon}</a><a class="social-icon" href="${INSTAGRAM_URL}" target="_blank" rel="noopener" aria-label="52 South on Instagram">${igIcon}</a>`;nav.appendChild(socialWrap);}
if(!document.getElementById('brand-social-fixes')){const style=document.createElement('style');style.id='brand-social-fixes';style.textContent=`
.brand img{border-radius:50%!important;overflow:hidden}.brand span{font-size:.92rem;letter-spacing:.035em;text-transform:none}.nav-socials{display:flex;gap:8px;align-items:center}.social-icon{width:34px;height:34px;border:1px solid #3a3a3a;border-radius:50%;display:inline-flex;align-items:center;justify-content:center;color:#f7f5f0}.social-icon svg{width:19px;height:19px}
.menu-toggle{width:48px;height:48px;padding:0!important;display:inline-flex!important;flex-direction:column;align-items:center;justify-content:center;gap:5px;border-radius:14px;line-height:1;background:rgba(15,15,15,.72);backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px)}.hamburger-line{display:block;width:22px;height:2px;border-radius:999px;background:#f6f4ef;transition:transform .25s ease,opacity .2s ease}.menu-toggle.active .hamburger-line:nth-child(1){transform:translateY(7px) rotate(45deg)}.menu-toggle.active .hamburger-line:nth-child(2){opacity:0}.menu-toggle.active .hamburger-line:nth-child(3){transform:translateY(-7px) rotate(-45deg)}
.hero .actions{perspective:950px;gap:16px}.hero .actions .btn{position:relative;overflow:hidden;border-radius:16px;padding:15px 24px;transform-style:preserve-3d;box-shadow:0 9px 0 rgba(0,0,0,.34),0 18px 34px rgba(0,0,0,.30),inset 0 1px rgba(255,255,255,.38);transition:transform .22s ease,box-shadow .22s ease,filter .22s ease}.hero .actions .btn:before{content:"";position:absolute;left:8px;right:8px;top:5px;height:42%;border-radius:12px;background:linear-gradient(180deg,rgba(255,255,255,.28),rgba(255,255,255,0));pointer-events:none}.hero .actions .btn:hover{transform:translateY(-7px) rotateX(4deg);box-shadow:0 14px 0 rgba(0,0,0,.32),0 28px 44px rgba(0,0,0,.40),inset 0 1px rgba(255,255,255,.45);filter:brightness(1.05)}.hero .actions .btn:active{transform:translateY(2px) scale(.985);box-shadow:0 3px 0 rgba(0,0,0,.32),0 8px 16px rgba(0,0,0,.25)}.hero .actions .btn.primary{background:linear-gradient(145deg,#fff,#dcdcdc);border-color:#fff;color:#111}.hero .actions .btn.gold{background:linear-gradient(145deg,#f1d083,#c79d4e);border-color:#edca77;color:#111}.hero .actions .btn:not(.primary):not(.gold){background:linear-gradient(145deg,rgba(30,30,30,.96),rgba(7,7,7,.98));border-color:rgba(255,255,255,.72);color:#fff;backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px)}
@media(max-width:800px){.brand span{font-size:.78rem;line-height:1.15;max-width:175px}.menu-toggle{width:46px;height:46px}.hero .actions{display:grid;grid-template-columns:1fr 1fr;gap:12px}.hero .actions .btn{text-align:center;padding:14px 12px;border-radius:14px;box-shadow:0 7px 0 rgba(0,0,0,.32),0 14px 24px rgba(0,0,0,.28)}.hero .actions .btn:hover{transform:none}.hero .actions .btn:active{transform:translateY(3px) scale(.98);box-shadow:0 3px 0 rgba(0,0,0,.30),0 7px 14px rgba(0,0,0,.22)}}
`;document.head.appendChild(style);}

/* Canva-powered Today cards. Automation refreshes these signed preview URLs. */
const TODAY_LUNCH_IMAGE='https://media.canva.com/v2/document-image/hash:-1921731868/height:447/id:DAHTuu8X2yM/type:B/width:447?brand=BACf_n-1sH4&csig=AAAAAAAAAAAAAAAAAAAAAEYXbCzpUbcjst4g0IJoVx_V4oIIHjytfAX71GPzYhsa&disableexport=T&exp=1788074593&fallback=https%3A%2F%2Fs3.amazonaws.com%2Fdocument-export.canva.com%2F8X2yM%2FDAHTuu8X2yM%2F3%2Fthumbnail%2F0001.png%3FX-Amz-Algorithm%3DAWS4-HMAC-SHA256%26X-Amz-Credential%3DAKIAQYCGKMUH4GDRW44L%252F20260829%252Fus-east-1%252Fs3%252Faws4_request%26X-Amz-Date%3D20260829T151915Z%26X-Amz-Expires%3D57838%26X-Amz-Signature%3Df3e5b08ac6f1b01db99c5f367041cec46d86d0dfba50ed6e497ecb90f821f04e%26X-Amz-SignedHeaders%3Dhost%26response-expires%3DSun%252C%252030%2520Aug%25202026%252007%253A23%253A13%2520GMT&osig=AAAAAAAAAAAAAAAAAAAAAO4Oo8E-p0USDLhCcJfymFqsUzplRlh36pvLy7lWhpzt&page=1&signed=brand%2Cdisableexport%2Cfallback%2Cpage%2Cversion&signer=document-rpc&version=3';
const LATEST_SPECIAL_IMAGE='https://media.canva.com/v2/document-image/hash:325865018/height:447/id:DAHTpqyzKq8/type:B/width:447?brand=BACf_n-1sH4&csig=AAAAAAAAAAAAAAAAAAAAABfdN5ievYp3n2uNmzQ6yyLZRyUFA4jY-bYB6Qaexq3w&disableexport=T&exp=1788074619&fallback=https%3A%2F%2Fs3.amazonaws.com%2Fdocument-export.canva.com%2FyzKq8%2FDAHTpqyzKq8%2F3%2Fthumbnail%2F0001.png%3FX-Amz-Algorithm%3DAWS4-HMAC-SHA256%26X-Amz-Credential%3DAKIAQYCGKMUH4GDRW44L%252F20260829%252Fus-east-1%252Fs3%252Faws4_request%26X-Amz-Date%3D20260829T234118Z%26X-Amz-Expires%3D27741%26X-Amz-Signature%3Db8003961be38cf7561b7f6a6b900a5f14a61da7a842d1ebda5456e0c304a668c%26X-Amz-SignedHeaders%3Dhost%26response-expires%3DSun%252C%252030%2520Aug%25202026%252007%253A23%253A39%2520GMT&osig=AAAAAAAAAAAAAAAAAAAAAO5uwW0ywmlH2q3Ya-oPjX5jGMjVvoShH21vJux2fw7H&page=1&signed=brand%2Cdisableexport%2Cfallback%2Cpage%2Cversion&signer=document-rpc&version=3';
const homeHero=document.querySelector('.hero');
if(homeHero&&!document.getElementById('experience-52')){const experience=document.createElement('section');experience.id='experience-52';experience.className='section experience-section';experience.innerHTML=`<div class="wrap"><div class="eyebrow">From our kitchen and dining room</div><h2>Come for the flavour. Stay for the welcome.</h2><p class="lede">A glimpse of the real dishes and relaxed space waiting for you at 52 South.</p><div class="experience-grid"><article class="experience-card wide"><video autoplay muted loop playsinline preload="metadata" poster="assets/52-south-interior-wide.webp"><source src="assets/52-south-venue-best-quality.mp4" type="video/mp4"></video><div><span>Inside 52 South</span><strong>A welcoming table in Rosetta</strong></div></article><article class="experience-card"><img src="assets/sri-lankan-rice-curry-plate.webp" alt="Sri Lankan rice and curry served at 52 South"><div><span>Made here</span><strong>Homestyle Sri Lankan food</strong></div></article><article class="experience-card"><img src="assets/sri-lankan-hoppers-promo.webp" alt="Fresh Sri Lankan hoppers at 52 South"><div><span>Friday and Saturday</span><strong>Fresh hoppers</strong></div></article></div><div class="actions"><a class="btn" href="/gallery/">See the gallery</a><a class="btn gold" href="/book-a-table/">Book a Table</a></div></div></section>`;homeHero.insertAdjacentElement('afterend',experience);}
if(homeHero&&!document.getElementById('today-at-52')){
  const today=document.createElement('section');today.id='today-at-52';today.className='section today-live-section';today.innerHTML=`<div class="wrap"><div class="eyebrow">Today at 52 South</div><h2>Lunch & Dinner Specials</h2><p class="lede">Rice & Curry is served from 12 PM. Swipe to see our latest dinner special.</p><div class="today-live-track"><article class="today-live-card lunch"><img src="${TODAY_LUNCH_IMAGE}" alt="Today's Rice and Curry Canva post"><div class="today-live-body"><span>Today’s Lunch</span><h3>Rice & Curry</h3><p>Served from 12 PM.</p><a class="btn gold" href="/menu/">View Menu</a></div></article><article class="today-live-card dinner"><img src="${LATEST_SPECIAL_IMAGE}" alt="Latest Dinner Special Canva post"><div class="today-live-body"><span>Latest Dinner / Special</span><h3>Dinner Special</h3><p>The latest special stays here until a new one is posted after 3 PM.</p><a class="btn gold" href="/menu/">View Menu</a></div></article></div><div class="today-live-hint"><span>☝︎</span> Swipe left for Dinner Special →</div></div>`;
  homeHero.insertAdjacentElement('afterend',today);
  const s=document.createElement('style');s.id='today-live-styles';s.textContent=`.today-live-section{background:linear-gradient(180deg,#0b0b0b,#111);overflow:hidden}.today-live-track{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-top:30px;perspective:1200px}.today-live-card{overflow:hidden;border-radius:24px;border:1px solid rgba(255,255,255,.12);transform-style:preserve-3d;box-shadow:12px 15px 0 rgba(0,0,0,.28),0 28px 60px rgba(0,0,0,.45);transition:transform .35s ease,box-shadow .35s ease}.today-live-card:hover{transform:translateY(-8px) rotateX(2deg);box-shadow:16px 21px 0 rgba(0,0,0,.26),0 38px 70px rgba(0,0,0,.52)}.today-live-card.lunch{background:linear-gradient(145deg,#17351f,#0b160f);border-color:#47875a}.today-live-card.dinner{background:linear-gradient(145deg,#3c1e14,#160c08);border-color:#a15339}.today-live-card img{display:block;width:100%;aspect-ratio:1/1;object-fit:cover;background:#151515}.today-live-body{padding:24px}.today-live-body>span{display:inline-block;padding:6px 10px;font-size:.75rem;font-weight:900;letter-spacing:.11em;text-transform:uppercase;color:#111;margin-bottom:8px}.lunch .today-live-body>span{background:#78ce8d}.dinner .today-live-body>span{background:#f08b61}.today-live-body h3{font-size:1.7rem;margin:4px 0}.today-live-body p{color:#c7c2bb}.today-live-hint{display:none}@media(max-width:800px){.today-live-track{display:grid;grid-auto-flow:column;grid-auto-columns:88%;grid-template-columns:none;overflow-x:auto;gap:16px;scroll-snap-type:x mandatory;-webkit-overflow-scrolling:touch;padding:4px 6% 26px 2px;scrollbar-width:none}.today-live-track::-webkit-scrollbar{display:none}.today-live-card{scroll-snap-align:center;box-shadow:8px 10px 0 rgba(0,0,0,.25),0 22px 42px rgba(0,0,0,.42)}.today-live-card:hover{transform:none}.today-live-hint{display:flex;align-items:center;justify-content:center;gap:8px;margin-top:6px;color:#e7d5aa;font-size:.88rem;font-weight:800}.today-live-hint span{display:inline-block;transform:rotate(90deg);animation:todaySwipe 1.5s ease-in-out infinite}}@keyframes todaySwipe{0%,100%{translate:-3px 0}50%{translate:5px 0}}`;
  document.head.appendChild(s);
}

const reviewsSection=document.getElementById('reviews');
if(reviewsSection&&!document.getElementById('guest-actions')){const guestActions=document.createElement('div');guestActions.id='guest-actions';guestActions.className='guest-actions';guestActions.innerHTML=`<div><strong>Enjoyed your visit?</strong><span>Your feedback helps more Hobart diners find us.</span></div><div class="actions"><a class="btn gold" href="https://www.google.com/maps/search/?api=1&query=52+South+Cafe+and+Restaurant+52+Marys+Hope+Road+Rosetta+TAS+7010" target="_blank" rel="noopener">Leave a Google Review</a><a class="btn" href="/loyalty/">Join 52 South Rewards</a></div>`;reviewsSection.querySelector('.wrap')?.appendChild(guestActions);}

const header=document.querySelector('.site-header');const syncHeader=()=>header&&header.classList.toggle('scrolled',window.scrollY>18);syncHeader();window.addEventListener('scroll',syncHeader,{passive:true});
const revealTargets=[...document.querySelectorAll('.section > .wrap, .card, .split > *, .scene, .info, .action-card, .menu-category, .gallery-grid img, .form-box, .review-card')];
revealTargets.forEach(el=>el.classList.add('reveal'));
const showAll=()=>revealTargets.forEach(el=>el.classList.add('in-view'));
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target);}});},{threshold:.05,rootMargin:'0px 0px 80px 0px'});revealTargets.forEach(el=>observer.observe(el));setTimeout(showAll,900);}else{showAll();}
window.addEventListener('pageshow',showAll);